[workspace]
resolver = "2"
members = [
  "dna/integrity_zomes/*",
  "dna/coordinator_zomes/*"
]

[workspace.dependencies]
hdk = "0.3.1"
hdi = "0.4.1"
serde = "1"
serde_json = "1"
holochain = "^0.3.1"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
